export enum ESimpleDataType {
  OTHER = "OTHER",
  DATE = "DATE",
  FLOAT = "FLOAT",
  DATETIME = "DATETIME",
  STRING = "STRING",
  INTEGER = "INTEGER",
  DATETIME64 = "DATETIME64",
  BOOLEAN = "BOOLEAN",
}
